#  Copyright (c) 2025-2026 by the Eozilla team and contributors
#  Permissions are hereby granted under the terms of the Apache 2.0 License:
#  https://opensource.org/license/apache-2-0.

import copy
from collections.abc import Sequence
from typing import Any

import pydantic

from gavicore.util.ensure import ensure_condition


def model_class_to_openapi_schema_dict(
    model_class: type[pydantic.BaseModel],
    *,
    inline_refs: bool = False,
    openapi_spec: str = "3.0",
) -> dict[str, Any]:
    """
    Convert a Pydantic model class to an OpenAPI schema `dict` object.

    Args:
        model_class: The Pydantic model class.
        inline_refs: Whether to inline any references (`$ref` values)
            generated by `model_class.model_json_schema()`.
        openapi_spec: The OpenAPI specification.
            Currently, only `"3.0"` is supported.
    Returns:
        An OpenAPI schema `dict` object.
    """
    model_class.model_rebuild()
    schema = model_class.model_json_schema()
    if inline_refs:
        schema = inline_schema_refs(schema)
    return json_schema_to_openapi_schema(schema, openapi_spec=openapi_spec)


def inline_schema_refs(schema: dict[str, Any] | bool) -> Any:
    if not isinstance(schema, dict):
        return schema
    defs: dict[str, Any] | None = schema.get("$defs")
    if not defs:
        return schema
    schema = copy.copy(schema)
    schema.pop("$defs")
    return _inline_schema_refs(schema, {f"#/$defs/{k}": v for k, v in defs.items()})


def _inline_schema_refs(schema: dict[str, Any] | bool, defs: dict[str, Any]) -> Any:
    if not isinstance(schema, dict):
        return schema
    if "$ref" in schema:
        ref = schema["$ref"]
        if ref in defs:
            ref_schema = _inline_schema_refs(defs[ref], defs)
            schema = copy.copy(schema)
            schema.pop("$ref")
            schema.update(copy.deepcopy(ref_schema))
            return schema
    schema = copy.copy(schema)
    for k in ("allOf", "anyOf", "oneOf"):
        if k in schema:
            if isinstance(schema[k], list):
                schema[k] = [_inline_schema_refs(s, defs) for s in schema[k]]
    for k in ("items", "prefixItems", "additionalProperties"):
        if k in schema:
            if isinstance(schema[k], list):
                schema[k] = [_inline_schema_refs(s, defs) for s in schema[k]]
            else:
                schema[k] = _inline_schema_refs(schema[k], defs)
    for k in ("properties",):
        if k in schema:
            if isinstance(schema[k], dict):
                schema[k] = {
                    k: _inline_schema_refs(s, defs) for k, s in schema[k].items()
                }
    return schema


def json_schema_to_openapi_schema(
    schema: dict[str, Any], *, openapi_spec: str = "3.0"
) -> dict[str, Any]:
    """
    Convert a JSON schema `dict` object into an OpenAPI schema `dict` object.

    Args:
        schema: A JSON schema `dict` object.
        openapi_spec: The OpenAPI specification.
            Currently, only `"3.0"` is supported.
    Returns:
        An OpenAPI schema `dict` object.
    """
    ensure_condition(openapi_spec == "3.0", "openapi_spec must be '3.0'")
    return _json_schema_to_openapi_schema_3_0(copy.deepcopy(schema))


def _json_schema_to_openapi_schema_3_0(schema: dict[str, Any]) -> dict[str, Any]:
    if "type" in schema:
        type_ = schema["type"]
        if type_ == "null":
            schema.pop("type")
            schema["nullable"] = True
    if "prefixItems" in schema:
        # This is how pydantic encodes tuples.
        items = schema.pop("prefixItems")
        if isinstance(items, (list, tuple)):
            schema["items"] = _json_tuple_to_openapi_items_3_0(items)
    if "items" in schema:
        items = schema.pop("items")
        if isinstance(items, (list, tuple)):
            schema["items"] = _json_tuple_to_openapi_items_3_0(items)
        elif isinstance(items, dict):
            schema["items"] = _json_schema_to_openapi_schema_3_0(items)
    if "additionalProperties" in schema:
        additional_properties = schema.pop("additionalProperties")
        if isinstance(additional_properties, dict):
            schema["additionalProperties"] = _json_schema_to_openapi_schema_3_0(
                additional_properties
            )
        elif additional_properties in (True, None):
            schema["additionalProperties"] = {}
        elif additional_properties is False:
            schema["additionalProperties"] = False
    for dict_key in ("properties", "$defs"):
        if dict_key in schema and isinstance(schema[dict_key], dict):
            schema[dict_key] = {
                k: _json_schema_to_openapi_schema_3_0(v)
                for k, v in schema[dict_key].items()
            }
    for x_of_key in ("allOf", "anyOf", "oneOf"):
        if x_of_key in schema:
            schema[x_of_key] = list(
                map(_json_schema_to_openapi_schema_3_0, schema[x_of_key])
            )
            if len(schema[x_of_key]) == 2:
                x_of_copy = [s for s in schema[x_of_key] if s != {"nullable": True}]
                if len(x_of_copy) == 1:
                    schema.pop(x_of_key)
                    schema.update(x_of_copy[0])
                    schema["nullable"] = True
    return schema


def _json_tuple_to_openapi_items_3_0(
    tuple_schemas: Sequence[dict[str, Any]],
) -> dict[str, Any]:
    """Convert a JSON schema tuple."""
    if not tuple_schemas:
        return {}
    converted = [_json_schema_to_openapi_schema_3_0(v) for v in tuple_schemas]
    c0 = converted[0]
    if all(c == c0 for c in converted[1:]):
        # If all items are the same schema,
        # we can take the first.
        return c0
    # As there is no way to represent tuples in OpenAPI <= 3.1,
    # we set items to oneOf of all tuple member schemas.
    return {"oneOf": converted}
