[project]
name = "s2gos-controller"
version = "0.0.6"
description = "S2GOS Monorepo"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[dependencies]
python = "3.13.*"
# IDE support
pixi-pycharm = "*"
# Development & Build tools
pip = "*"
hatch = "*"
# Code Style / QA
isort = "*"
ruff = "*"
# Unit-Testing
pytest = "*"
pytest-cov = "*"
# GUI testing
ipyleaflet = "*"
ipywidgets = "*"
ipywidgets_bokeh = "*"
jupyter = "*"
notebook = "*"
panel = "*"
watchfiles = "*"
# Use cases testing
dask = "*"
xarray = "*"
zarr = "*"
# Code-generation from tools/
datamodel-code-generator = "*"
# Doku
mkdocs = "*"
mkdocs-autorefs = "*"
mkdocs-material = "*"
mkdocstrings = "*"
mkdocstrings-python = "*"

[pypi-dependencies]
s2gos-common = { path = "./s2gos-common", editable = true }
s2gos-client = { path = "./s2gos-client", editable = true }
s2gos-server = { path = "./s2gos-server", editable = true }

[tool.pixi]
workspaces = ["s2gos-common", "s2gos-server", "s2gos-client"]

[tasks.develop]
cmd = "pip install -e s2gos-common && pip install -e s2gos-server && pip install -e s2gos-client"

[tasks.codegen]
cmd = "python tools/gen_models.py && python tools/gen_server.py && python tools/gen_client.py"

[tasks.docs-serve]
cmd = "mkdocs serve"

[tasks.docs-build]
cmd = "mkdocs build"

[tasks.test]
cmd = "pytest"
