[project]
name = "s2gos-controller"
version = "0.0.6"
description = "S2GOS Monorepo"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[dependencies]
python = "3.13.*"
pixi-pycharm = ">=0.0.8,<0.0.9"
# Development & Build tools
pip = "*"
hatch = "*"
# Code Style / QA
ruff = "*"
# Unit-Testing
pytest = "*"
pytest-cov = "*"
# GUI testing
ipyleaflet = "*"
ipywidgets = "*"
ipywidgets_bokeh = "*"
jupyter = "*"
notebook = "*"
panel = "*"
watchfiles = "*"
# Use cases testing
dask = "*"
xarray = "*"
zarr = "*"
# Code-generation from tools/
datamodel-code-generator = "*"
# Doku
mkdocs = "*"
mkdocs-autorefs = "*"
mkdocs-material = "*"
mkdocstrings = "*"
mkdocstrings-python = "*"

[pypi-dependencies]
s2gos-common = { path = "s2gos-common", editable = true }
s2gos-client = { path = "s2gos-client", editable = true }
s2gos-server = { path = "s2gos-server", editable = true }

[tool.ruff]
include = [
    "pixi.toml",
    "tools/**/*.py",
    "s2gos-common/src/**/*.py",
    "s2gos-server/src/**/*.py",
    "s2gos-client/src/**/*.py",
]

[tool.ruff.lint]
ignore = ["E501", "F821"]
isort = { relative-imports-order = "closest-to-furthest" }
per-file-ignores = { "*.ipynb" = ["E402"] }
select = ["I", "F", "E"]

[tasks.codegen]
cmd = "python tools/gen_models.py && python tools/gen_server.py && python tools/gen_client.py"

[tasks.test-common]
cmd = "pytest s2gos-common/src/tests"

[tasks.cov-common]
cmd = "pytest --cov s2gos-common/src/s2gos_common --cov-report html s2gos-common/src/tests"

[tasks.test-server]
cmd = "pytest s2gos-server/src/tests"

[tasks.cov-server]
cmd = "pytest --cov s2gos-server/src/s2gos_server --cov-report html s2gos-server/src/tests"

[tasks.test-client]
cmd = "pytest s2gos-client/src/tests"

[tasks.cov-client]
cmd = "pytest --cov s2gos-client/src/s2gos_client --cov-report html s2gos-client/src/tests"


[tasks.docs-serve]
cmd = "mkdocs serve"

[tasks.docs-build]
cmd = "mkdocs build"

