# generated by gen_server.py:
#   filename:  routes.py:
#   timestamp: 2026-05-27T07:55:14.099104

import fastapi

from gavicore.models import (
    Capabilities,
    ConformanceDeclaration,
    JobInfo,
    JobList,
    JobResults,
    ProcessDescription,
    ProcessList,
    ProcessRequest,
)
from gavicore.service import Service

from .app import app
from .provider import get_service


# noinspection PyPep8Naming
@app.get(
    "/",
    response_model=Capabilities,
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def get_capabilities(
    request: fastapi.Request,
    response: fastapi.Response,
    service: Service = fastapi.Depends(get_service),  # noqa B008
):
    return await service.get_capabilities(request=request, response=response)


# noinspection PyPep8Naming
@app.get(
    "/conformance",
    response_model=ConformanceDeclaration,
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def get_conformance(
    request: fastapi.Request,
    response: fastapi.Response,
    service: Service = fastapi.Depends(get_service),  # noqa B008
):
    return await service.get_conformance(request=request, response=response)


# noinspection PyPep8Naming
@app.get(
    "/processes",
    response_model=ProcessList,
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def get_processes(
    request: fastapi.Request,
    response: fastapi.Response,
    service: Service = fastapi.Depends(get_service),  # noqa B008
):
    return await service.get_processes(request=request, response=response)


# noinspection PyPep8Naming
@app.get(
    "/processes/{processID}",
    response_model=ProcessDescription,
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def get_process(
    processID: str,
    request: fastapi.Request,
    response: fastapi.Response,
    service: Service = fastapi.Depends(get_service),  # noqa B008
):
    return await service.get_process(
        process_id=processID, request=request, response=response
    )


# noinspection PyPep8Naming
@app.post(
    "/processes/{processID}/execution",
    status_code=201,
    response_model=JobInfo,
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def execute_process(
    processID: str,
    process_request: ProcessRequest,
    request: fastapi.Request,
    response: fastapi.Response,
    service: Service = fastapi.Depends(get_service),  # noqa B008
):
    return await service.execute_process(
        process_id=processID,
        process_request=process_request,
        request=request,
        response=response,
    )


# noinspection PyPep8Naming
@app.get(
    "/jobs",
    response_model=JobList,
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def get_jobs(
    request: fastapi.Request,
    response: fastapi.Response,
    service: Service = fastapi.Depends(get_service),  # noqa B008
):
    return await service.get_jobs(request=request, response=response)


# noinspection PyPep8Naming
@app.get(
    "/jobs/{jobId}",
    response_model=JobInfo,
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def get_job(
    jobId: str,
    request: fastapi.Request,
    response: fastapi.Response,
    service: Service = fastapi.Depends(get_service),  # noqa B008
):
    return await service.get_job(job_id=jobId, request=request, response=response)


# noinspection PyPep8Naming
@app.delete(
    "/jobs/{jobId}",
    response_model=JobInfo,
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def dismiss_job(
    jobId: str,
    request: fastapi.Request,
    response: fastapi.Response,
    service: Service = fastapi.Depends(get_service),  # noqa B008
):
    return await service.dismiss_job(job_id=jobId, request=request, response=response)


# noinspection PyPep8Naming
@app.get(
    "/jobs/{jobId}/results",
    response_model=JobResults,
    response_model_exclude_none=True,
    response_model_exclude_unset=True,
)
async def get_job_results(
    jobId: str,
    request: fastapi.Request,
    response: fastapi.Response,
    service: Service = fastapi.Depends(get_service),  # noqa B008
):
    return await service.get_job_results(
        job_id=jobId, request=request, response=response
    )
