#  Copyright (c) 2026 by the Eozilla team and contributors
#  Permissions are hereby granted under the terms of the Apache 2.0 License:
#  https://opensource.org/license/apache-2-0.

from pathlib import Path

import pytest

from appligator.airflow.gen_dockerfile import (
    _copy_pyproject_toml_stripped,
    generate,
)

def _workspace(tmp_path: Path, *, packages: list[str] | None = None) -> Path:
    """Create a minimal pixi workspace under tmp_path."""
    (tmp_path / "pyproject.toml").write_text("[project]\nname = 'test'\n")
    (tmp_path / "pixi.lock").write_text("# lock\n")
    if packages:
        for pkg in packages:
            pkg_dir = tmp_path / "packages" / pkg
            pkg_dir.mkdir(parents=True)
            (pkg_dir / "pyproject.toml").write_text(
                f"[project]\nname = '{pkg}'\n"
            )
    return tmp_path


def _gen(tmp_path: Path, **kwargs) -> tuple[Path, str]:
    """Call gen_dockerfile from a workspace root and return (dockerfile_path, content)."""
    ws = _workspace(tmp_path, packages=kwargs.pop("_packages", None))
    out = tmp_path / "image"
    import os

    old = os.getcwd()
    os.chdir(ws)
    try:
        df = generate(output_dir=out, **kwargs)
    finally:
        os.chdir(old)
    return df, df.read_text()


class TestValidation:
    def test_unsupported_package_manager_raises(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        with pytest.raises(ValueError, match="Unsupported package manager"):
            generate(package_manager="uv", output_dir=tmp_path / "out")

    def test_local_packages_without_packages_dir_raises(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        with pytest.raises(ValueError, match="local_packages requires packages_dir"):
            generate(
                output_dir=tmp_path / "out",
                local_packages=["my-pkg"],
            )

    def test_missing_pyproject_toml_raises(self, tmp_path, monkeypatch):
        (tmp_path / "pixi.lock").write_text("")
        monkeypatch.chdir(tmp_path)
        with pytest.raises(FileNotFoundError, match="pyproject.toml"):
            generate(output_dir=tmp_path / "out")

    def test_missing_pixi_lock_raises(self, tmp_path, monkeypatch):
        (tmp_path / "pyproject.toml").write_text("")
        monkeypatch.chdir(tmp_path)
        with pytest.raises(FileNotFoundError, match="pixi.lock"):
            generate(output_dir=tmp_path / "out")

    def test_extra_files_missing_source_raises(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        with pytest.raises(FileNotFoundError, match="extra_files entry"):
            generate(
                output_dir=tmp_path / "out",
                extra_files={"data": tmp_path / "nonexistent"},
            )

    def test_local_packages_missing_package_raises(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path)
        pkgs_dir = ws / "packages"
        pkgs_dir.mkdir()
        monkeypatch.chdir(ws)
        with pytest.raises(FileNotFoundError, match="not found in"):
            generate(
                output_dir=tmp_path / "out",
                packages_dir=pkgs_dir,
                local_packages=["nonexistent-pkg"],
            )


class TestOutputDir:
    def test_returns_dockerfile_path(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        df = generate(output_dir=tmp_path / "out")
        assert df == tmp_path / "out" / "Dockerfile"
        assert df.exists()

    def test_output_dir_recreated_if_exists(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        out = tmp_path / "out"
        out.mkdir()
        (out / "stale.txt").write_text("old")
        generate(output_dir=out)
        assert not (out / "stale.txt").exists()

    def test_workspace_files_copied(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        out = tmp_path / "out"
        generate(output_dir=out)
        assert (out / "pyproject.toml").exists()
        assert (out / "pixi.lock").exists()

    def test_run_step_copied(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        out = tmp_path / "out"
        generate(output_dir=out)
        assert (out / "run_step.py").exists()


class TestDockerfileContent:
    def test_header_comment(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path)
        assert "Generated by appligator" in content

    def test_entrypoint_is_last_meaningful_line(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path)
        lines = [l for l in content.splitlines() if l.strip()]
        assert lines[-1] == 'ENTRYPOINT ["python", "/opt/pixi/run_step.py"]'

    def test_default_pixi_version(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path)
        assert "ghcr.io/prefix-dev/pixi:0.50.2-bookworm-slim" in content

    def test_custom_pixi_version(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path, pixi_version="0.42.0")
        assert "ghcr.io/prefix-dev/pixi:0.42.0-bookworm-slim" in content

    def test_default_workdir(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path)
        assert "WORKDIR /opt/pixi" in content

    def test_custom_workdir(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path, workdir="/app")
        assert "WORKDIR /app" in content
        assert "/opt/pixi" not in content

    def test_default_pixi_env(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path)
        assert "pixi install --locked -e default" in content
        assert ".pixi/envs/default" in content

    def test_custom_pixi_env(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path, pixi_env="prod")
        assert "pixi install --locked -e prod" in content
        assert ".pixi/envs/prod" in content

    def test_libgomp1_always_present(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path)
        assert "libgomp1" in content

    def test_runtime_apt_packages(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path, runtime_apt_packages=["gdal-bin", "curl"])
        assert "gdal-bin" in content
        assert "curl" in content
        assert "libgomp1" in content

    def test_build_commands_before_pixi_install(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path, build_commands=["RUN pixi add some-pkg"])
        assert content.index("RUN pixi add some-pkg") < content.index(
            "pixi install --locked"
        )

    def test_runtime_commands_in_runtime_stage(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(
            tmp_path,
            runtime_commands=["RUN echo hello", "COPY ./foo /app/foo"],
        )
        runtime_start = content.index("FROM debian:bookworm-slim")
        assert content.index("RUN echo hello") > runtime_start
        assert content.index("COPY ./foo /app/foo") > runtime_start

    def test_runtime_commands_before_entrypoint(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        _, content = _gen(tmp_path, runtime_commands=["RUN echo hello"])
        assert content.index("RUN echo hello") < content.index("ENTRYPOINT")


# ── packages_dir ──────────────────────────────────────────────────────────────


class TestPackagesDir:
    def test_packages_copied_to_build_context(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path, packages=["my-pkg"])
        monkeypatch.chdir(ws)
        out = tmp_path / "out"
        generate(
            output_dir=out,
            packages_dir=ws / "packages",
            local_packages=["my-pkg"],
        )
        assert (out / "packages" / "my-pkg").is_dir()

    def test_only_listed_packages_copied(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path, packages=["pkg-a", "pkg-b", "pkg-c"])
        monkeypatch.chdir(ws)
        out = tmp_path / "out"
        generate(
            output_dir=out,
            packages_dir=ws / "packages",
            local_packages=["pkg-a"],
        )
        assert (out / "packages" / "pkg-a").is_dir()
        assert not (out / "packages" / "pkg-b").exists()
        assert not (out / "packages" / "pkg-c").exists()

    def test_packages_copy_instruction_in_build_stage(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path, packages=["my-pkg"])
        monkeypatch.chdir(ws)
        _, content = _gen(
            tmp_path,
            packages_dir=ws / "packages",
            local_packages=["my-pkg"],
        )
        build_stage = content[: content.index("FROM debian:bookworm-slim")]
        assert "COPY ./packages ./packages" in build_stage

    def test_packages_not_copied_to_runtime_when_local_packages_set(
        self, tmp_path, monkeypatch
    ):
        ws = _workspace(tmp_path, packages=["my-pkg"])
        monkeypatch.chdir(ws)
        _, content = _gen(
            tmp_path,
            packages_dir=ws / "packages",
            local_packages=["my-pkg"],
        )
        runtime_stage = content[content.index("FROM debian:bookworm-slim") :]
        assert "COPY --from=build" not in runtime_stage or (
            "/packages" not in runtime_stage
        )

    def test_packages_copied_to_runtime_when_no_local_packages(
        self, tmp_path, monkeypatch
    ):
        ws = _workspace(tmp_path, packages=["my-pkg"])
        monkeypatch.chdir(ws)
        _, content = _gen(tmp_path, packages_dir=ws / "packages")
        runtime_stage = content[content.index("FROM debian:bookworm-slim") :]
        assert "COPY --from=build" in runtime_stage
        assert "/packages" in runtime_stage

    def test_custom_packages_dirname_used_in_dockerfile(
        self, tmp_path, monkeypatch
    ):
        ws = tmp_path / "ws"
        ws.mkdir()
        (ws / "pyproject.toml").write_text("[project]\nname = 'test'\n")
        (ws / "pixi.lock").write_text("# lock\n")
        libs = ws / "libs"
        (libs / "my-pkg").mkdir(parents=True)
        (libs / "my-pkg" / "pyproject.toml").write_text("")
        monkeypatch.chdir(ws)
        _, content = _gen(
            tmp_path,
            packages_dir=libs,
            local_packages=["my-pkg"],
        )
        assert "COPY ./libs ./libs" in content


# ── local_packages / pip install ──────────────────────────────────────────────


class TestLocalPackages:
    def test_pip_install_command_generated(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path, packages=["my-pkg"])
        monkeypatch.chdir(ws)
        _, content = _gen(
            tmp_path,
            packages_dir=ws / "packages",
            local_packages=["my-pkg"],
        )
        assert "pip install --no-deps --no-build-isolation" in content
        assert "./packages/my-pkg" in content

    def test_pip_path_uses_workdir_and_pixi_env(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path, packages=["my-pkg"])
        monkeypatch.chdir(ws)
        _, content = _gen(
            tmp_path,
            workdir="/app",
            pixi_env="prod",
            packages_dir=ws / "packages",
            local_packages=["my-pkg"],
        )
        assert "/app/.pixi/envs/prod/bin/pip" in content

    def test_pip_install_after_pixi_install(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path, packages=["my-pkg"])
        monkeypatch.chdir(ws)
        _, content = _gen(
            tmp_path,
            packages_dir=ws / "packages",
            local_packages=["my-pkg"],
        )
        assert content.index("pip install") > content.index("pixi install --locked")

    def test_multiple_local_packages(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path, packages=["pkg-a", "pkg-b"])
        monkeypatch.chdir(ws)
        _, content = _gen(
            tmp_path,
            packages_dir=ws / "packages",
            local_packages=["pkg-a", "pkg-b"],
        )
        assert "./packages/pkg-a" in content
        assert "./packages/pkg-b" in content

    def test_post_install_commands_appended_after_pip(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path, packages=["my-pkg"])
        monkeypatch.chdir(ws)
        _, content = _gen(
            tmp_path,
            packages_dir=ws / "packages",
            local_packages=["my-pkg"],
            post_install_commands=["RUN echo done"],
        )
        assert content.index("pip install") < content.index("RUN echo done")


class TestExtraFiles:
    def test_extra_file_copied(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path)
        data = ws / "data.csv"
        data.write_text("a,b\n")
        monkeypatch.chdir(ws)
        out = tmp_path / "out"
        generate(output_dir=out, extra_files={"data.csv": data})
        assert (out / "data.csv").exists()

    def test_extra_dir_copied(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path)
        d = ws / "assets"
        d.mkdir()
        (d / "file.txt").write_text("x")
        monkeypatch.chdir(ws)
        out = tmp_path / "out"
        generate(output_dir=out, extra_files={"assets": d})
        assert (out / "assets" / "file.txt").exists()


class TestCopyPyprojectTomlStripped:
    def test_sibling_path_dep_stripped(self, tmp_path):
        src = tmp_path / "pyproject.toml"
        src.write_text(
            "[tool.pixi.pypi-dependencies]\n"
            'appligator = { path = "../eozilla/appligator", editable = true }\n'
        )
        dest = tmp_path / "out.toml"
        _copy_pyproject_toml_stripped(src, dest)
        import tomllib

        data = tomllib.loads(dest.read_text())
        assert "appligator" not in data["tool"]["pixi"]["pypi-dependencies"]

    def test_absolute_path_dep_stripped(self, tmp_path):
        src = tmp_path / "pyproject.toml"
        src.write_text(
            "[tool.pixi.pypi-dependencies]\n"
            'mypkg = { path = "/home/user/mypkg", editable = true }\n'
        )
        dest = tmp_path / "out.toml"
        _copy_pyproject_toml_stripped(src, dest)
        import tomllib

        data = tomllib.loads(dest.read_text())
        assert "mypkg" not in data["tool"]["pixi"]["pypi-dependencies"]

    def test_local_packages_dep_kept(self, tmp_path):
        src = tmp_path / "pyproject.toml"
        src.write_text(
            "[tool.pixi.pypi-dependencies]\n"
            'mypkg = { path = "packages/mypkg", editable = true }\n'
        )
        dest = tmp_path / "out.toml"
        _copy_pyproject_toml_stripped(src, dest)
        import tomllib

        data = tomllib.loads(dest.read_text())
        assert "mypkg" in data["tool"]["pixi"]["pypi-dependencies"]

    def test_feature_path_dep_stripped(self, tmp_path):
        src = tmp_path / "pyproject.toml"
        src.write_text(
            "[tool.pixi.feature.local-deps.pypi-dependencies]\n"
            'appligator = { path = "../eozilla/appligator", editable = true }\n'
        )
        dest = tmp_path / "out.toml"
        _copy_pyproject_toml_stripped(src, dest)
        import tomllib

        data = tomllib.loads(dest.read_text())
        feature_deps = (
            data["tool"]["pixi"]["feature"]["local-deps"]["pypi-dependencies"]
        )
        assert "appligator" not in feature_deps
