#  Copyright (c) 2026 by the Eozilla team and contributors
#  Permissions are hereby granted under the terms of the Apache 2.0 License:
#  https://opensource.org/license/apache-2-0.

import types
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from appligator.airflow.gen_image import EOZILLA_PACKAGES, _render_dockerfile, gen_image


# ── helpers ───────────────────────────────────────────────────────────────────


def _make_registry(step_modules: list[str] | None = None):
    """Return a minimal registry-like object with the given module names."""
    steps = {}
    for i, module_name in enumerate(step_modules or []):
        mock_fn = MagicMock()
        mock_fn.__module__ = module_name
        steps[f"step_{i}"] = {"step": MagicMock(function=mock_fn)}
    registry = MagicMock()
    registry.steps = steps
    return registry


def _workspace(tmp_path: Path, *, packages_dir: bool = False) -> Path:
    """Create a minimal pixi workspace under tmp_path."""
    (tmp_path / "pyproject.toml").write_text("[project]\nname = 'test'\n")
    (tmp_path / "pixi.lock").write_text("# lock\n")
    if packages_dir:
        (tmp_path / "packages" / "mypkg").mkdir(parents=True)
        (tmp_path / "packages" / "mypkg" / "__init__.py").write_text("")
    return tmp_path


class TestRenderDockerfile:
    def _render(self, **kwargs):
        defaults = dict(
            use_local_packages=False,
            has_packages_dir=False,
            pixi_version="0.50.2",
            runtime_apt_packages=None,
            step_module_filenames=[],
            dockerfile_extra=None,
            build_stage_extra=None,
        )
        defaults.update(kwargs)
        return _render_dockerfile(**defaults)

    def test_header_comment(self):
        out = self._render()
        assert "# Generated by appligator" in out
        assert "do not edit by hand" in out

    def test_stage1_uses_pixi_version(self):
        out = self._render(pixi_version="0.42.0")
        assert "ghcr.io/prefix-dev/pixi:0.42.0-bookworm-slim" in out

    def test_stage2_base_image(self):
        out = self._render()
        assert "FROM debian:bookworm-slim" in out

    def test_entrypoint_is_last_meaningful_line(self):
        out = self._render()
        lines = [l for l in out.splitlines() if l.strip()]
        assert lines[-1] == 'ENTRYPOINT ["python", "/opt/pixi/run_step.py"]'

    def test_packages_dir_copies_in_both_stages(self):
        out = self._render(has_packages_dir=True)
        assert "COPY ./packages" in out
        assert "COPY --from=build /opt/pixi/packages" in out

    def test_no_packages_dir_by_default(self):
        out = self._render(has_packages_dir=False)
        assert "packages" not in out

    def test_use_local_packages_copies_all_eozilla_pkgs(self):
        out = self._render(use_local_packages=True)
        for pkg in EOZILLA_PACKAGES:
            assert f"COPY ./{pkg}" in out
            assert f"COPY --from=build /opt/pixi/{pkg}" in out

    def test_no_local_packages_by_default(self):
        out = self._render(use_local_packages=False)
        for pkg in EOZILLA_PACKAGES:
            assert f"COPY ./{pkg}" not in out

    def test_runtime_apt_packages_included(self):
        out = self._render(runtime_apt_packages=["gdal-bin", "curl"])
        assert "gdal-bin" in out
        assert "curl" in out
        # libgomp1 is always present
        assert "libgomp1" in out

    def test_libgomp1_always_present(self):
        out = self._render(runtime_apt_packages=None)
        assert "libgomp1" in out

    def test_step_module_filenames_copied(self):
        out = self._render(step_module_filenames=["my_steps.py", "helpers.py"])
        assert "COPY ./my_steps.py /opt/pixi/my_steps.py" in out
        assert "COPY ./helpers.py /opt/pixi/helpers.py" in out

    def test_dockerfile_extra_appended_before_entrypoint(self):
        extra = "RUN echo hello\nENV FOO=bar"
        out = self._render(dockerfile_extra=extra)
        extra_pos = out.index("RUN echo hello")
        entry_pos = out.index("ENTRYPOINT")
        assert extra_pos < entry_pos

    def test_dockerfile_extra_none_leaves_no_extra_lines(self):
        out = self._render(dockerfile_extra=None)
        assert "RUN echo" not in out

    def test_build_stage_extra_inserted_before_pixi_install(self):
        out = self._render(build_stage_extra="RUN pixi add some-package")
        extra_pos = out.index("RUN pixi add some-package")
        install_pos = out.index("RUN pixi install --locked")
        assert extra_pos < install_pos

    def test_build_stage_extra_none_leaves_no_extra_lines(self):
        out = self._render(build_stage_extra=None)
        assert "RUN pixi add" not in out


class TestGenImage:
    @pytest.fixture(autouse=True)
    def _mock_docker(self):
        """Prevent real docker calls in every test."""
        with patch("appligator.airflow.gen_image.subprocess.check_call") as mock_call, \
             patch("appligator.airflow.gen_image.shutil.which", return_value="/usr/bin/docker"):
            self._check_call = mock_call
            yield

    def test_returns_image_name(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        result = gen_image(_make_registry(), image_name="myrepo/myimage:latest",
                           output_dir=tmp_path / "out")
        assert result == "myrepo/myimage:latest"

    def test_calls_docker_build(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        out = tmp_path / "out"
        gen_image(_make_registry(), image_name="myrepo/img:v1", output_dir=out)
        self._check_call.assert_called_once()
        cmd = self._check_call.call_args[0][0]
        assert cmd == ["/usr/bin/docker", "build", "-t", "myrepo/img:v1", "."]

    def test_output_dir_recreated_if_exists(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        out = tmp_path / "out"
        out.mkdir()
        (out / "stale.txt").write_text("old")
        gen_image(_make_registry(), image_name="img:latest", output_dir=out)
        assert not (out / "stale.txt").exists()

    def test_pyproject_and_lock_copied(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        out = tmp_path / "out"
        gen_image(_make_registry(), image_name="img:latest", output_dir=out)
        assert (out / "pyproject.toml").exists()
        assert (out / "pixi.lock").exists()

    def test_dockerfile_written(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        out = tmp_path / "out"
        gen_image(_make_registry(), image_name="img:latest", output_dir=out)
        assert (out / "Dockerfile").exists()
        assert "ENTRYPOINT" in (out / "Dockerfile").read_text()

    def test_run_step_copied(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        out = tmp_path / "out"
        gen_image(_make_registry(), image_name="img:latest", output_dir=out)
        assert (out / "run_step.py").exists()

    def test_packages_dir_copied_when_present(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path, packages_dir=True))
        out = tmp_path / "out"
        gen_image(_make_registry(), image_name="img:latest", output_dir=out)
        assert (out / "packages").is_dir()

    def test_packages_dir_not_required(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path, packages_dir=False))
        out = tmp_path / "out"
        gen_image(_make_registry(), image_name="img:latest", output_dir=out)
        assert not (out / "packages").exists()

    def test_use_local_packages_copies_existing_pkg(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path)
        # create a fake local eozilla package dir
        pkg = EOZILLA_PACKAGES[0]
        (ws / pkg / "src").mkdir(parents=True)
        monkeypatch.chdir(ws)
        out = tmp_path / "out"
        gen_image(_make_registry(), image_name="img:latest",
                  use_local_packages=True, output_dir=out)
        assert (out / pkg).is_dir()

    def test_use_local_packages_skips_missing_pkg(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        out = tmp_path / "out"
        # no local package dirs exist — should not raise
        gen_image(_make_registry(), image_name="img:latest",
                  use_local_packages=True, output_dir=out)

    def test_extra_files_file_copied(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path)
        data_file = ws / "data.csv"
        data_file.write_text("a,b\n1,2\n")
        monkeypatch.chdir(ws)
        out = tmp_path / "out"
        gen_image(_make_registry(), image_name="img:latest", output_dir=out,
                  extra_files={"data.csv": data_file})
        assert (out / "data.csv").exists()

    def test_extra_files_dir_copied(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path)
        d = ws / "assets"
        d.mkdir()
        (d / "file.txt").write_text("x")
        monkeypatch.chdir(ws)
        out = tmp_path / "out"
        gen_image(_make_registry(), image_name="img:latest", output_dir=out,
                  extra_files={"assets": d})
        assert (out / "assets" / "file.txt").exists()

    def test_extra_files_missing_source_raises(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        with pytest.raises(FileNotFoundError, match="extra_files entry"):
            gen_image(_make_registry(), image_name="img:latest",
                      output_dir=tmp_path / "out",
                      extra_files={"missing": tmp_path / "nonexistent"})

    def test_invalid_image_name_raises(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        with pytest.raises(ValueError, match="Invalid image name"):
            gen_image(_make_registry(), image_name="bad name!",
                      output_dir=tmp_path / "out")

    def test_docker_not_found_raises(self, tmp_path, monkeypatch):
        monkeypatch.chdir(_workspace(tmp_path))
        with patch("appligator.airflow.gen_image.shutil.which", return_value=None):
            with pytest.raises(RuntimeError, match="docker executable not found"):
                gen_image(_make_registry(), image_name="img:latest",
                          output_dir=tmp_path / "out")

    def test_missing_pyproject_toml_raises(self, tmp_path, monkeypatch):
        tmp_path.mkdir(exist_ok=True)
        (tmp_path / "pixi.lock").write_text("")
        monkeypatch.chdir(tmp_path)
        with pytest.raises(FileNotFoundError, match="pyproject.toml"):
            gen_image(_make_registry(), image_name="img:latest",
                      output_dir=tmp_path / "out")

    def test_missing_pixi_lock_raises(self, tmp_path, monkeypatch):
        tmp_path.mkdir(exist_ok=True)
        (tmp_path / "pyproject.toml").write_text("")
        monkeypatch.chdir(tmp_path)
        with pytest.raises(FileNotFoundError, match="pixi.lock"):
            gen_image(_make_registry(), image_name="img:latest",
                      output_dir=tmp_path / "out")

    def test_step_module_file_copied(self, tmp_path, monkeypatch):
        ws = _workspace(tmp_path)
        step_file = ws / "my_steps.py"
        step_file.write_text("def my_step(): pass\n")
        monkeypatch.chdir(ws)

        mock_module = MagicMock(spec=types.ModuleType)
        mock_module.__file__ = str(step_file)
        with patch("appligator.airflow.gen_image.importlib.import_module", return_value=mock_module):
            out = tmp_path / "out"
            gen_image(_make_registry(["my_module"]), image_name="img:latest", output_dir=out)

        assert (out / "my_steps.py").exists()
