#  Copyright (c) 2026 by the Eozilla team and contributors
#  Permissions are hereby granted under the terms of the Apache 2.0 License:
#  https://opensource.org/license/apache-2-0.

import keyword
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final, Protocol

from gavicore.models import DataType, InputDescription, ProcessDescription, Schema

TAB: Final[str] = "    "


@dataclass(frozen=True)
class GeneratedServiceClients:
    """Python source code for generated sync and async service clients."""

    sync_module_name: str
    async_module_name: str
    sync_class_name: str
    async_class_name: str
    sync_code: str
    async_code: str


class _ProcessMetadataClient(Protocol):
    def get_processes(self) -> Any: ...

    def get_process(self, process_id: str) -> ProcessDescription: ...


def fetch_process_descriptions(
    client: _ProcessMetadataClient,
) -> list[ProcessDescription]:
    """Fetch all process descriptions from a cuiman-compatible client."""
    process_list = client.get_processes()
    return [client.get_process(process.id) for process in process_list.processes]


def write_service_client_modules(
    name: str,
    process_descriptions: list[ProcessDescription],
    output_dir: str | Path,
) -> dict[str, Path]:
    """Generate and write sync and async service-client modules."""
    generated = generate_service_client_modules(name, process_descriptions)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    sync_path = output_path / f"{generated.sync_module_name}.py"
    async_path = output_path / f"{generated.async_module_name}.py"
    sync_path.write_text(generated.sync_code)
    async_path.write_text(generated.async_code)
    return {"sync": sync_path, "async": async_path}


def generate_service_client_modules(
    name: str, process_descriptions: list[ProcessDescription]
) -> GeneratedServiceClients:
    """Generate sync and async Python modules for a service."""
    module_name = _to_identifier(name).lower()
    class_name = _to_pascal_case(name)
    sync_module_name = f"{module_name}_{_SYNC_CLIENT.module_suffix}"
    async_module_name = f"{module_name}_{_ASYNC_CLIENT.module_suffix}"
    sync_class_name = f"{class_name}{_SYNC_CLIENT.class_suffix}"
    async_class_name = f"{class_name}{_ASYNC_CLIENT.class_suffix}"
    method_specs = _new_method_specs(process_descriptions)
    return GeneratedServiceClients(
        sync_module_name=sync_module_name,
        async_module_name=async_module_name,
        sync_class_name=sync_class_name,
        async_class_name=async_class_name,
        sync_code=_render_module(
            class_name=sync_class_name,
            client_type=_SYNC_CLIENT,
            method_specs=method_specs,
        ),
        async_code=_render_module(
            class_name=async_class_name,
            client_type=_ASYNC_CLIENT,
            method_specs=method_specs,
        ),
    )


@dataclass(frozen=True)
class _MethodSpec:
    process_id: str
    name: str
    title: str | None
    description: str | None
    inputs: list["_InputSpec"]


@dataclass(frozen=True)
class _InputSpec:
    original_name: str
    param_name: str
    type_hint: str
    default_code: str | None
    omit_when_none: bool
    title: str | None
    description: str | None


@dataclass(frozen=True)
class _ClientTypeSpec:
    module_suffix: str
    class_suffix: str
    base_module: str
    base_class_name: str
    helper_name: str
    is_async: bool


_SYNC_CLIENT = _ClientTypeSpec(
    module_suffix="sync",
    class_suffix="Client",
    base_module="cuiman.api.client",
    base_class_name="Client",
    helper_name="execute_and_open_result",
    is_async=False,
)
_ASYNC_CLIENT = _ClientTypeSpec(
    module_suffix="async",
    class_suffix="AsyncClient",
    base_module="cuiman.api.async_client",
    base_class_name="AsyncClient",
    helper_name="async_execute_and_open_result",
    is_async=True,
)


def _render_module(
    *,
    class_name: str,
    client_type: _ClientTypeSpec,
    method_specs: list[_MethodSpec],
) -> str:
    lines = [
        "# generated by cuiman",
        "",
        "from typing import Any",
        "",
        f"from {client_type.base_module} import {client_type.base_class_name}",
        f"from cuiman.api.jobs import JobOptions, {client_type.helper_name}",
        "from gavicore.models import ProcessRequest",
        "",
        f"__all__ = [{class_name!r}]",
        "",
        "",
        f"class {class_name}({client_type.base_class_name}):",
    ]
    if not method_specs:
        lines.extend(_indent_lines(["pass"], 1))
    for index, method_spec in enumerate(method_specs):
        if index:
            lines.append("")
        method_lines = _render_method(method_spec, client_type=client_type)
        lines.extend(_indent_lines(method_lines, 1))
    return _lines_to_code(lines)


def _render_method(spec: _MethodSpec, *, client_type: _ClientTypeSpec) -> list[str]:
    async_prefix = "async " if client_type.is_async else ""
    lines = [f"{async_prefix}def {spec.name}("]
    lines.extend(_indent_lines(_render_parameters(spec.inputs), 1))
    lines.append(") -> Any:")

    body = _render_method_docstring(spec)
    body.append("inputs: dict[str, Any] = {}")
    body.extend(_render_input_assignments(spec.inputs))
    body.append("request = ProcessRequest(inputs=inputs)")
    await_prefix = "await " if client_type.is_async else ""
    body.append(f"return {await_prefix}{client_type.helper_name}(")
    body.extend(
        _indent_lines(
            [
                "self,",
                f"{spec.process_id!r},",
                "request,",
                "job_options=job_options,",
            ],
            1,
        )
    )
    body.append(")")
    lines.extend(_indent_lines(body, 1))
    return lines


def _render_parameters(inputs: list[_InputSpec]) -> list[str]:
    parameters = ["self,", "*,"]
    for input_spec in inputs:
        default = (
            f" = {input_spec.default_code}"
            if input_spec.default_code is not None
            else ""
        )
        parameters.append(f"{input_spec.param_name}: {input_spec.type_hint}{default},")
    parameters.append("job_options: JobOptions | None = None,")
    return parameters


def _render_input_assignments(inputs: list[_InputSpec]) -> list[str]:
    lines: list[str] = []
    for input_spec in inputs:
        assignment = f"inputs[{input_spec.original_name!r}] = {input_spec.param_name}"
        if input_spec.omit_when_none:
            lines.append(f"if {input_spec.param_name} is not None:")
            lines.extend(_indent_lines([assignment], 1))
        else:
            lines.append(assignment)
    return lines


def _render_method_docstring(spec: _MethodSpec) -> list[str]:
    lines = [f"Execute process ``{spec.process_id}`` and return its opened result."]
    if spec.title:
        lines.append("")
        lines.extend(_clean_doc_line(line) for line in spec.title.split("\n"))
    if spec.description:
        lines.append("")
        lines.extend(_clean_doc_line(line) for line in spec.description.split("\n"))
    lines.extend(["", "Args:"])
    for input_spec in spec.inputs:
        desc = input_spec.description or input_spec.title or "Process input."
        lines.append(f"{TAB}{input_spec.param_name}: {_clean_doc_line(desc)}")
    lines.append(
        f"{TAB}job_options: Optional job execution and result-opening options."
    )
    lines.append("")
    lines.append("Raises:")
    lines.append(
        f"{TAB}ClientError: If the API call, job execution, or result opening fails."
    )
    escaped_lines = [line.replace('"""', r"\"\"\"") for line in lines]
    return [f'"""{escaped_lines[0]}', *escaped_lines[1:], '"""']


def _new_method_specs(
    process_descriptions: list[ProcessDescription],
) -> list[_MethodSpec]:
    used_method_names: set[str] = set()
    method_specs: list[_MethodSpec] = []
    for process_description in process_descriptions:
        method_name = _unique_identifier(
            _to_identifier(process_description.id), used_method_names
        )
        used_method_names.add(method_name)
        method_specs.append(
            _MethodSpec(
                process_id=process_description.id,
                name=method_name,
                title=process_description.title,
                description=process_description.description,
                inputs=_new_input_specs(process_description.inputs or {}),
            )
        )
    return method_specs


def _new_input_specs(
    input_descriptions: dict[str, InputDescription],
) -> list[_InputSpec]:
    used_param_names = {"self", "job_options"}
    input_specs: list[_InputSpec] = []
    for input_name, input_description in input_descriptions.items():
        param_name = _unique_identifier(_to_identifier(input_name), used_param_names)
        used_param_names.add(param_name)
        default_code, omit_when_none = _get_default_code(input_description)
        input_specs.append(
            _InputSpec(
                original_name=input_name,
                param_name=param_name,
                type_hint=_get_type_hint(
                    input_description.schema_,
                    include_none=default_code == "None"
                    or _is_nullable(input_description),
                ),
                default_code=default_code,
                omit_when_none=omit_when_none,
                title=input_description.title,
                description=input_description.description,
            )
        )
    return input_specs


def _get_default_code(input_description: InputDescription) -> tuple[str | None, bool]:
    schema = input_description.schema_
    if schema and "default" in schema.model_fields_set:
        return repr(schema.default), False
    if input_description.minOccurs == 0:
        return "None", True
    return None, False


def _get_type_hint(schema: Schema | None, *, include_none: bool = False) -> str:
    type_hint = _get_base_type_hint(schema)
    if include_none and "None" not in type_hint.split(" | "):
        return f"{type_hint} | None"
    return type_hint


def _get_base_type_hint(schema: Schema | None) -> str:
    if schema is None:
        return "Any"
    data_type = schema.type
    if data_type == DataType.boolean:
        return "bool"
    if data_type == DataType.integer:
        return "int"
    if data_type == DataType.number:
        return "float"
    if data_type == DataType.string:
        return "str"
    if data_type == DataType.array:
        item_hint = _get_base_type_hint(schema.items)
        return f"list[{item_hint}]"
    if data_type == DataType.object:
        return "dict[str, Any]"
    return "Any"


def _is_nullable(input_description: InputDescription) -> bool:
    schema = input_description.schema_
    return bool(schema and schema.nullable)


def _to_identifier(value: str) -> str:
    identifier = re.sub(r"\W+", "_", value.strip()).strip("_")
    if not identifier:
        identifier = "value"
    if identifier[0].isdigit():
        identifier = f"_{identifier}"
    if keyword.iskeyword(identifier):
        identifier = f"{identifier}_"
    return identifier


def _unique_identifier(identifier: str, used: set[str]) -> str:
    if identifier not in used:
        return identifier
    identifier_with_suffix = f"{identifier}_"
    if identifier_with_suffix not in used:
        return identifier_with_suffix
    index = 2
    while f"{identifier}_{index}" in used:
        index += 1
    return f"{identifier}_{index}"


def _to_pascal_case(value: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", value)
    if not parts:
        return "Service"
    return "".join(part[:1].upper() + part[1:] for part in parts)


def _clean_doc_line(value: str) -> str:
    return " ".join(value.split())


def _lines_to_code(lines: list[str]) -> str:
    return "\n".join(lines) + "\n"


def _indent_lines(lines: list[str], indentations: int) -> list[str]:
    indent = indentations * TAB
    return [indent + line if line else line for line in lines]
