#  Copyright (c) 2026 by the Eozilla team and contributors
#  Permissions are hereby granted under the terms of the Apache 2.0 License:
#  https://opensource.org/license/apache-2-0.

import keyword
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

from gavicore.models import DataType, InputDescription, ProcessDescription, Schema


@dataclass(frozen=True)
class GeneratedServiceClients:
    """Python source code for generated sync and async service clients."""

    sync_module_name: str
    async_module_name: str
    sync_class_name: str
    async_class_name: str
    sync_code: str
    async_code: str


class _ProcessMetadataClient(Protocol):
    def get_processes(self) -> Any: ...

    def get_process(self, process_id: str) -> ProcessDescription: ...


def fetch_process_descriptions(
    client: _ProcessMetadataClient,
) -> list[ProcessDescription]:
    """Fetch all process descriptions from a cuiman-compatible client."""
    process_list = client.get_processes()
    return [client.get_process(process.id) for process in process_list.processes]


def write_service_client_modules(
    name: str,
    process_descriptions: list[ProcessDescription],
    output_dir: str | Path,
) -> dict[str, Path]:
    """Generate and write sync and async service-client modules."""
    generated = generate_service_client_modules(name, process_descriptions)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    sync_path = output_path / f"{generated.sync_module_name}.py"
    async_path = output_path / f"{generated.async_module_name}.py"
    sync_path.write_text(generated.sync_code)
    async_path.write_text(generated.async_code)
    return {"sync": sync_path, "async": async_path}


def generate_service_client_modules(
    name: str, process_descriptions: list[ProcessDescription]
) -> GeneratedServiceClients:
    """Generate sync and async Python modules for a service."""
    module_name = _to_identifier(name).lower()
    class_name = _to_pascal_case(name)
    sync_module_name = f"{module_name}_sync"
    async_module_name = f"{module_name}_async"
    sync_class_name = f"{class_name}Client"
    async_class_name = f"{class_name}AsyncClient"
    method_specs = _new_method_specs(process_descriptions)
    return GeneratedServiceClients(
        sync_module_name=sync_module_name,
        async_module_name=async_module_name,
        sync_class_name=sync_class_name,
        async_class_name=async_class_name,
        sync_code=_render_module(
            class_name=sync_class_name,
            base_import="from cuiman.api.client import Client",
            base_class_name="Client",
            helper_import=(
                "from cuiman.api.jobs import JobOptions, execute_and_open_result"
            ),
            helper_name="execute_and_open_result",
            method_specs=method_specs,
            is_async=False,
        ),
        async_code=_render_module(
            class_name=async_class_name,
            base_import="from cuiman.api.async_client import AsyncClient",
            base_class_name="AsyncClient",
            helper_import=(
                "from cuiman.api.jobs import JobOptions, async_execute_and_open_result"
            ),
            helper_name="async_execute_and_open_result",
            method_specs=method_specs,
            is_async=True,
        ),
    )


@dataclass(frozen=True)
class _MethodSpec:
    process_id: str
    name: str
    title: str | None
    description: str | None
    inputs: list["_InputSpec"]


@dataclass(frozen=True)
class _InputSpec:
    original_name: str
    param_name: str
    type_hint: str
    default_code: str | None
    omit_when_none: bool
    title: str | None
    description: str | None


def _render_module(
    *,
    class_name: str,
    base_import: str,
    base_class_name: str,
    helper_import: str,
    helper_name: str,
    method_specs: list[_MethodSpec],
    is_async: bool,
) -> str:
    methods = "\n\n".join(
        _render_method(spec, helper_name=helper_name, is_async=is_async)
        for spec in method_specs
    )
    if not methods:
        methods = "    pass\n"
    return (
        "# generated by cuiman\n\n"
        "from typing import Any\n\n"
        f"{base_import}\n"
        f"{helper_import}\n"
        "from gavicore.models import ProcessRequest\n\n"
        f"__all__ = [{class_name!r}]\n\n\n"
        f"class {class_name}({base_class_name}):\n"
        f"{methods}"
    )


def _render_method(spec: _MethodSpec, *, helper_name: str, is_async: bool) -> str:
    params = _render_params(spec.inputs)
    docstring = _render_method_docstring(spec)
    inputs = _render_inputs(spec.inputs)
    await_ = "await " if is_async else ""
    async_ = "async " if is_async else ""
    return (
        f"    {async_}def {spec.name}(\n"
        "        self,\n"
        f"{params}"
        "        job_options: JobOptions | None = None,\n"
        "    ) -> Any:\n"
        f"{docstring}"
        "        inputs: dict[str, Any] = {}\n"
        f"{inputs}"
        "        request = ProcessRequest(inputs=inputs)\n"
        f"        return {await_}{helper_name}(\n"
        "            self,\n"
        f"            {spec.process_id!r},\n"
        "            request,\n"
        "            job_options=job_options,\n"
        "        )\n"
    )


def _render_params(inputs: list[_InputSpec]) -> str:
    if not inputs:
        return "        *,\n"
    params = ["        *,\n"]
    for input_spec in inputs:
        default = (
            f" = {input_spec.default_code}"
            if input_spec.default_code is not None
            else ""
        )
        params.append(
            f"        {input_spec.param_name}: {input_spec.type_hint}{default},\n"
        )
    return "".join(params)


def _render_inputs(inputs: list[_InputSpec]) -> str:
    if not inputs:
        return ""
    lines = []
    for input_spec in inputs:
        if input_spec.omit_when_none:
            lines.append(f"        if {input_spec.param_name} is not None:\n")
            lines.append(
                f"            inputs[{input_spec.original_name!r}] = "
                f"{input_spec.param_name}\n"
            )
        else:
            lines.append(
                f"        inputs[{input_spec.original_name!r}] = "
                f"{input_spec.param_name}\n"
            )
    return "".join(lines)


def _render_method_docstring(spec: _MethodSpec) -> str:
    lines = [f"Execute process ``{spec.process_id}`` and return its opened result."]
    tab = 4 * " "
    indent = 2 * tab
    if spec.title:
        lines.append("")
        lines.extend([indent + _clean_doc_line(l) for l in spec.title.split("\n")])
    if spec.description:
        lines.append("")
        lines.extend(
            [indent + _clean_doc_line(l) for l in spec.description.split("\n")]
        )
    lines.extend(["", f"{indent}Args:"])
    for input_spec in spec.inputs:
        desc = input_spec.description or input_spec.title or "Process input."
        lines.append(f"{indent}{tab}{input_spec.param_name}: {_clean_doc_line(desc)}")
    lines.append(
        f"{indent}{tab}job_options: Optional job execution and result-opening options."
    )
    lines.append("")
    lines.append(f"{indent}Raises:")
    lines.append(
        f"{indent}{tab}ClientError: If the API call, job execution, or result opening fails."
    )
    doc = "\n".join(lines).replace('"""', r"\"\"\"")
    return f'        """{doc}\n        """\n'


def _new_method_specs(
    process_descriptions: list[ProcessDescription],
) -> list[_MethodSpec]:
    used_method_names: set[str] = set()
    method_specs: list[_MethodSpec] = []
    for process_description in process_descriptions:
        method_name = _unique_identifier(
            _to_identifier(process_description.id), used_method_names
        )
        used_method_names.add(method_name)
        method_specs.append(
            _MethodSpec(
                process_id=process_description.id,
                name=method_name,
                title=process_description.title,
                description=process_description.description,
                inputs=_new_input_specs(process_description.inputs or {}),
            )
        )
    return method_specs


def _new_input_specs(
    input_descriptions: dict[str, InputDescription],
) -> list[_InputSpec]:
    used_param_names = {"self", "job_options"}
    input_specs: list[_InputSpec] = []
    for input_name, input_description in input_descriptions.items():
        param_name = _unique_identifier(_to_identifier(input_name), used_param_names)
        used_param_names.add(param_name)
        default_code, omit_when_none = _get_default_code(input_description)
        input_specs.append(
            _InputSpec(
                original_name=input_name,
                param_name=param_name,
                type_hint=_get_type_hint(
                    input_description.schema_,
                    include_none=default_code == "None"
                    or _is_nullable(input_description),
                ),
                default_code=default_code,
                omit_when_none=omit_when_none,
                title=input_description.title,
                description=input_description.description,
            )
        )
    return input_specs


def _get_default_code(input_description: InputDescription) -> tuple[str | None, bool]:
    schema = input_description.schema_
    if schema and "default" in schema.model_fields_set:
        return repr(schema.default), False
    if input_description.minOccurs == 0:
        return "None", True
    return None, False


def _get_type_hint(schema: Schema | None, *, include_none: bool = False) -> str:
    type_hint = _get_base_type_hint(schema)
    if include_none and "None" not in type_hint.split(" | "):
        return f"{type_hint} | None"
    return type_hint


def _get_base_type_hint(schema: Schema | None) -> str:
    if schema is None:
        return "Any"
    data_type = schema.type
    if data_type == DataType.boolean:
        return "bool"
    if data_type == DataType.integer:
        return "int"
    if data_type == DataType.number:
        return "float"
    if data_type == DataType.string:
        return "str"
    if data_type == DataType.array:
        item_hint = _get_base_type_hint(schema.items)
        return f"list[{item_hint}]"
    if data_type == DataType.object:
        return "dict[str, Any]"
    return "Any"


def _is_nullable(input_description: InputDescription) -> bool:
    schema = input_description.schema_
    return bool(schema and schema.nullable)


def _to_identifier(value: str) -> str:
    identifier = re.sub(r"\W+", "_", value.strip()).strip("_")
    if not identifier:
        identifier = "value"
    if identifier[0].isdigit():
        identifier = f"_{identifier}"
    if keyword.iskeyword(identifier):
        identifier = f"{identifier}_"
    return identifier


def _unique_identifier(identifier: str, used: set[str]) -> str:
    if identifier not in used:
        return identifier
    identifier_with_suffix = f"{identifier}_"
    if identifier_with_suffix not in used:
        return identifier_with_suffix
    index = 2
    while f"{identifier}_{index}" in used:
        index += 1
    return f"{identifier}_{index}"


def _to_pascal_case(value: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", value)
    if not parts:
        return "Service"
    return "".join(part[:1].upper() + part[1:] for part in parts)


def _clean_doc_line(value: str) -> str:
    return " ".join(value.split())
