name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pixi-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pixi (with optional auth token)
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIXDEV_AUTH_TOKEN }}

      - name: Run Tests
        run: pixi run test

      # Add other pixi tasks here

