name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pixi-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIXDEV_AUTH_TOKEN }}

      - name: Run checks
        run: pixi run lint

      - name: Run test & coverage
        run: pixi run coverage-ci

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Add other pixi tasks here

